SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 기존 테이블 데이터 자르기
TRUNCATE TABLE TBL_SCORE;
--==>> Table TBL_MEMBER이(가) 잘렸습니다.

--○ 기존 시퀀스 제거
DROP SEQUENCE SCORESEQ;
--==>> Sequence SCORESEQ이(가) 삭제되었습니다.


--○ 실습 관련 시퀀스 다시 생성
CREATE SEQUENCE SCORESEQ
NOCACHE;
--==>> Sequence SCORESEQ이(가) 생성되었습니다.

--○ 추가 샘플 데이터 입력
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '박제훈', 80, 70, 60)
;
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '안석창', 70, 60, 50)
;
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '정영훈', 50, 40, 30)
;

SELECT *
FROM TBL_SCORE;
--==>>
/*
1	정승민	90	80	70
2	박제훈	80	70	60
3	안석창	70	60	50
4	정영훈	50	40	30
5	곽유진	100	50	40
8	곽유진2	65	78	100
9	곽유진3	65	77	99
*/

DESC TBL_SCORE;

--○ 인원수 조회 쿼리
SELECT COUNT(*) AS COUNT
FROM TBL_SCORE;
--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;
--==>> 7


--○ 전체 조회 쿼리
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, ROUND((KOR+ENG+MAT)/3, 1) AS AVG
FROM TBL_SCORE
ORDER BY SID;
--> 한 줄 구성
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, ROUND((KOR+ENG+MAT)/3, 1) AS AVG FROM TBL_SCORE ORDER BY SID
;

--○ 데이터 추가 쿼리
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '곽유진', 100, 90, 80)
;

--○커밋
COMMIT;

--○ 데이터 삭제 쿼리
DELETE
FROM TBL_SCORE
WHERE SID=5;
-->한 줄 구성
DELETE FROM TBL_SCORE WHERE SID=5
;
